// Code generated by "stringer -type=ServerPacket,ClientPacket -output=packet_enum_string.go"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IncAlertMSG-1]
	_ = x[IncLoginOk-2]
	_ = x[IncClassesData-3]
	_ = x[IncInGame-4]
	_ = x[IncPlayerInvUpdate-5]
	_ = x[IncPlayerWornEquipment-6]
	_ = x[IncPlayerVitals-7]
	_ = x[IncCoins-8]
	_ = x[IncSkulls-9]
	_ = x[IncPlayerStats-10]
	_ = x[IncPlayerData-11]
	_ = x[IncPlayerMove-12]
	_ = x[IncNpcMove-13]
	_ = x[IncPlayerDir-14]
	_ = x[IncNpcDir-15]
	_ = x[IncPlayerXY-16]
	_ = x[IncAttack-17]
	_ = x[IncNpcAttack-18]
	_ = x[IncCheckMap-19]
	_ = x[IncMapData-20]
	_ = x[IncMapItemData-21]
	_ = x[IncMapNPCData-22]
	_ = x[IncSteamAchievement-23]
	_ = x[IncGlobalMessage-24]
	_ = x[IncPlayerMessage-25]
	_ = x[IncMapMessage-26]
	_ = x[IncSpawnItem-27]
	_ = x[IncUpdateItem-28]
	_ = x[IncSpawnNPC-29]
	_ = x[IncNpcDead-30]
	_ = x[IncUpdateNPC-31]
	_ = x[IncUpdateShop-32]
	_ = x[IncUpdateSpell-33]
	_ = x[IncSpells-34]
	_ = x[IncPlayerTimer-35]
	_ = x[IncResourceCache-36]
	_ = x[IncUpdateResource-37]
	_ = x[IncPing-38]
	_ = x[IncActionMessage-39]
	_ = x[IncPlayerExp-40]
	_ = x[IncPlayerSprite-41]
	_ = x[IncUpdateAnimation-42]
	_ = x[IncAnimation-43]
	_ = x[IncMapNpcVitals-44]
	_ = x[IncCooldown-45]
	_ = x[IncClearSpellBuffer-46]
	_ = x[IncSayMessage-47]
	_ = x[IncOpenShop-48]
	_ = x[IncInspectPlayer-49]
	_ = x[IncStunned-50]
	_ = x[IncMapWornEquipment-51]
	_ = x[IncBank-52]
	_ = x[IncUpdateNewspaper-53]
	_ = x[IncPlayerCurrent-54]
	_ = x[IncClose-55]
	_ = x[IncTradeUpdate-56]
	_ = x[IncTradeStatus-57]
	_ = x[IncGameData-58]
	_ = x[IncHighIndex-59]
	_ = x[IncTarget-60]
	_ = x[IncCharData-61]
	_ = x[IncDefensa-62]
	_ = x[IncUpdateQuest-63]
	_ = x[IncPlayerQuest-64]
	_ = x[IncSendTime-65]
	_ = x[IncSolarEXP-66]
	_ = x[IncPlayerInvite-67]
	_ = x[IncPartyUpdate-68]
	_ = x[IncPartyVitals-69]
	_ = x[IncBossMsg-70]
	_ = x[IncPlayerXYMap-71]
	_ = x[IncProjectil-72]
	_ = x[IncUpdateProjectil-73]
	_ = x[IncUpdateMoral-74]
	_ = x[IncFlash-75]
	_ = x[IncRequestEditor-76]
	_ = x[IncUpdateCard-77]
	_ = x[IncPlayerCards-78]
	_ = x[IncUpdateCrafting-79]
	_ = x[IncPlayerCrafting-80]
	_ = x[IncPlayerDeath-81]
	_ = x[IncUpdateTitle-82]
	_ = x[IncPlayerDataType-83]
	_ = x[IncBuffInfo-84]
	_ = x[IncSpellAnim-85]
	_ = x[IncBattleMsg-86]
	_ = x[IncNPCProjectil-87]
	_ = x[IncMapSound-88]
	_ = x[IncArrow-89]
	_ = x[IncBandit-90]
	_ = x[IncPlayerGameData-91]
	_ = x[IncPVP-92]
	_ = x[IncMapTopoData-93]
	_ = x[IncTopoDrill-94]
	_ = x[IncUpdateCondition-95]
	_ = x[IncServerMsg-96]
	_ = x[IncDailyCheck-97]
	_ = x[IncSpawnMobItem-98]
	_ = x[IncProjectilCross-99]
	_ = x[IncReceiveHour-100]
	_ = x[IncReceiveBubble-101]
	_ = x[IncChoice-102]
	_ = x[IncClearChoice-103]
	_ = x[IncGetAdminInfo-104]
	_ = x[IncBreakPoint-105]
	_ = x[IncUpdateMapEvent-106]
	_ = x[IncSendConditionVar-107]
	_ = x[IncSendPlayerVars-108]
	_ = x[IncQuestMsg-109]
	_ = x[IncUpdatePuzzle-110]
	_ = x[IncUpdatePuzzleCache-111]
	_ = x[IncUpdatePlayerList-112]
	_ = x[IncCombo-113]
	_ = x[IncTutorial-114]
	_ = x[IncPlayerElement-115]
	_ = x[IncPlayerRank-116]
	_ = x[IncEarthquake-117]
	_ = x[IncEventRank-118]
	_ = x[IncTravelInfo-119]
	_ = x[IncLoginBackOK-120]
	_ = x[IncPlayerAwards-121]
	_ = x[IncAwards-122]
	_ = x[IncCharacterConfirm-123]
	_ = x[IncOpenUI-124]
	_ = x[IncLogOutOK-125]
	_ = x[IncPlayerScore-126]
	_ = x[IncPartyQuestInfo-127]
	_ = x[IncDemoUpdateQuest-128]
	_ = x[IncCashInvUpdate-129]
	_ = x[IncPlayerInfo-130]
	_ = x[IncPlayerHonor-131]
	_ = x[IncPlayerBuddies-132]
	_ = x[IncBuddiesAction-133]
	_ = x[IncDrillBreak-134]
	_ = x[IncArenaBonus-136]
	_ = x[IncNpcBuffInfo-137]
	_ = x[IncAnnouncer-138]
	_ = x[IncOpenBackground-139]
	_ = x[IncCouponReady-140]
	_ = x[IncProfessionStart-141]
	_ = x[IncModifier-142]
	_ = x[IncPlayerMaster-143]
	_ = x[IncUrl-144]
	_ = x[IncPlayerStatus-145]
	_ = x[IncPlayerConnected-146]
	_ = x[IncServerStats-147]
	_ = x[IncGetModInfo-148]
	_ = x[IncPlayerTrap-149]
	_ = x[IncShowEmoticon-150]
	_ = x[IncProfessionData-151]
	_ = x[IncServerVars-152]
	_ = x[IncCashShopData-153]
	_ = x[IncBlockList-154]
	_ = x[IncConstantData-155]
}

const (
	_ServerPacket_name_0 = "IncAlertMSGIncLoginOkIncClassesDataIncInGameIncPlayerInvUpdateIncPlayerWornEquipmentIncPlayerVitalsIncCoinsIncSkullsIncPlayerStatsIncPlayerDataIncPlayerMoveIncNpcMoveIncPlayerDirIncNpcDirIncPlayerXYIncAttackIncNpcAttackIncCheckMapIncMapDataIncMapItemDataIncMapNPCDataIncSteamAchievementIncGlobalMessageIncPlayerMessageIncMapMessageIncSpawnItemIncUpdateItemIncSpawnNPCIncNpcDeadIncUpdateNPCIncUpdateShopIncUpdateSpellIncSpellsIncPlayerTimerIncResourceCacheIncUpdateResourceIncPingIncActionMessageIncPlayerExpIncPlayerSpriteIncUpdateAnimationIncAnimationIncMapNpcVitalsIncCooldownIncClearSpellBufferIncSayMessageIncOpenShopIncInspectPlayerIncStunnedIncMapWornEquipmentIncBankIncUpdateNewspaperIncPlayerCurrentIncCloseIncTradeUpdateIncTradeStatusIncGameDataIncHighIndexIncTargetIncCharDataIncDefensaIncUpdateQuestIncPlayerQuestIncSendTimeIncSolarEXPIncPlayerInviteIncPartyUpdateIncPartyVitalsIncBossMsgIncPlayerXYMapIncProjectilIncUpdateProjectilIncUpdateMoralIncFlashIncRequestEditorIncUpdateCardIncPlayerCardsIncUpdateCraftingIncPlayerCraftingIncPlayerDeathIncUpdateTitleIncPlayerDataTypeIncBuffInfoIncSpellAnimIncBattleMsgIncNPCProjectilIncMapSoundIncArrowIncBanditIncPlayerGameDataIncPVPIncMapTopoDataIncTopoDrillIncUpdateConditionIncServerMsgIncDailyCheckIncSpawnMobItemIncProjectilCrossIncReceiveHourIncReceiveBubbleIncChoiceIncClearChoiceIncGetAdminInfoIncBreakPointIncUpdateMapEventIncSendConditionVarIncSendPlayerVarsIncQuestMsgIncUpdatePuzzleIncUpdatePuzzleCacheIncUpdatePlayerListIncComboIncTutorialIncPlayerElementIncPlayerRankIncEarthquakeIncEventRankIncTravelInfoIncLoginBackOKIncPlayerAwardsIncAwardsIncCharacterConfirmIncOpenUIIncLogOutOKIncPlayerScoreIncPartyQuestInfoIncDemoUpdateQuestIncCashInvUpdateIncPlayerInfoIncPlayerHonorIncPlayerBuddiesIncBuddiesActionIncDrillBreak"
	_ServerPacket_name_1 = "IncArenaBonusIncNpcBuffInfoIncAnnouncerIncOpenBackgroundIncCouponReadyIncProfessionStartIncModifierIncPlayerMasterIncUrlIncPlayerStatusIncPlayerConnectedIncServerStatsIncGetModInfoIncPlayerTrapIncShowEmoticonIncProfessionDataIncServerVarsIncCashShopDataIncBlockListIncConstantData"
)

var (
	_ServerPacket_index_0 = [...]uint16{0, 11, 21, 35, 44, 62, 84, 99, 107, 116, 130, 143, 156, 166, 178, 187, 198, 207, 219, 230, 240, 254, 267, 286, 302, 318, 331, 343, 356, 367, 377, 389, 402, 416, 425, 439, 455, 472, 479, 495, 507, 522, 540, 552, 567, 578, 597, 610, 621, 637, 647, 666, 673, 691, 707, 715, 729, 743, 754, 766, 775, 786, 796, 810, 824, 835, 846, 861, 875, 889, 899, 913, 925, 943, 957, 965, 981, 994, 1008, 1025, 1042, 1056, 1070, 1087, 1098, 1110, 1122, 1137, 1148, 1156, 1165, 1182, 1188, 1202, 1214, 1232, 1244, 1257, 1272, 1289, 1303, 1319, 1328, 1342, 1357, 1370, 1387, 1406, 1423, 1434, 1449, 1469, 1488, 1496, 1507, 1523, 1536, 1549, 1561, 1574, 1588, 1603, 1612, 1631, 1640, 1651, 1665, 1682, 1700, 1716, 1729, 1743, 1759, 1775, 1788}
	_ServerPacket_index_1 = [...]uint16{0, 13, 27, 39, 56, 70, 88, 99, 114, 120, 135, 153, 167, 180, 193, 208, 225, 238, 253, 265, 280}
)

func (i ServerPacket) String() string {
	switch {
	case 1 <= i && i <= 134:
		i -= 1
		return _ServerPacket_name_0[_ServerPacket_index_0[i]:_ServerPacket_index_0[i+1]]
	case 136 <= i && i <= 155:
		i -= 136
		return _ServerPacket_name_1[_ServerPacket_index_1[i]:_ServerPacket_index_1[i+1]]
	default:
		return "ServerPacket(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutSaveResource-45]
	_ = x[OutSaveNpc-31]
	_ = x[OutSaveItem-30]
	_ = x[OutSavePuzzle-101]
	_ = x[OutSaveSpell-33]
	_ = x[OutSaveShop-32]
	_ = x[OutSaveAnimation-50]
	_ = x[OutProjectilAttack-81]
	_ = x[OutSaveProjectil-80]
	_ = x[OutSaveMoral-82]
	_ = x[OutSaveCard-84]
	_ = x[OutSaveCrafting-86]
	_ = x[OutSaveMapTopo-93]
	_ = x[OutSteamTransaction-94]
	_ = x[OutSaveCondition-95]
	_ = x[OutSaveConditionVar-100]
	_ = x[OutSaveQuest-73]
	_ = x[OutCheckAttack-12]
	_ = x[OutCheckTopo-91]
	_ = x[OutCheckDefensa-69]
	_ = x[OutHandlePressEnter-14]
	_ = x[OutCastingSpell-42]
	_ = x[OutPVP-92]
	_ = x[OutMapEditorCancel-22]
	_ = x[OutRequestEditor-83]
	_ = x[OutSelected-74]
	_ = x[OutNewAccount-1]
	_ = x[OutAddChar-3]
	_ = x[OutLogin-2]
	_ = x[OutGetPing-46]
	_ = x[OutChangeSpellSlots-70]
	_ = x[OutHotbarChange-71]
	_ = x[OutMap-21]
	_ = x[OutPlayerDir-10]
	_ = x[OutSayMsg-8]
	_ = x[OutReportPlayer-26]
	_ = x[OutBan-29]
	_ = x[OutHotkeys-13]
	_ = x[OutWarpMeTo-15]
	_ = x[OutWarpToMe-16]
	_ = x[OutAdminTask-17]
	_ = x[OutSetAccess-34]
	_ = x[OutTakeCapture-43]
	_ = x[OutSpawnItem-48]
	_ = x[OutRequestLevelUp-51]
	_ = x[OutChangePassword-18]
	_ = x[OutLoginBack-103]
	_ = x[OutWhisper-75]
	_ = x[OutHotbarUse-72]
	_ = x[OutUseMegaphone-19]
	_ = x[OutClientRevision-20]
	_ = x[OutSaveCombo-102]
	_ = x[OutPartyLeave-79]
	_ = x[OutPartyRequest-76]
	_ = x[OutReplyPlayerInvitation-77]
	_ = x[OutDeclineParty-78]
	_ = x[OutRequestData-85]
	_ = x[OutEnhancement-28]
	_ = x[OutMapRespawn-25]
	_ = x[OutTrainStat-49]
	_ = x[OutDragItem-7]
	_ = x[OutProfessionEnd-6]
	_ = x[OutPlayerMsg-5]
	_ = x[OutWhosOnline-35]
	_ = x[OutTryOpenUI-36]
	_ = x[OutBanList-27]
	_ = x[OutSwapSlots-44]
	_ = x[OutUseItem-11]
	_ = x[OutUseCashItem-106]
	_ = x[OutDropCalaveras-110]
	_ = x[OutDropItem-24]
	_ = x[OutBuyItem-54]
	_ = x[OutSellItem-55]
	_ = x[OutDepositItem-57]
	_ = x[OutWithdrawItem-58]
	_ = x[OutChangeBankSlots-56]
	_ = x[OutCloseBank-59]
	_ = x[OutPlayerSearch-37]
	_ = x[OutTradeRequest-61]
	_ = x[OutAdminWarp-60]
	_ = x[OutUnequip-47]
	_ = x[OutAcceptTrade-62]
	_ = x[OutDeclineTrade-63]
	_ = x[OutTradeItem-64]
	_ = x[OutUntradeItem-65]
	_ = x[OutRequestUseChar-66]
	_ = x[OutRequestNewChar-67]
	_ = x[OutRequestDelChar-68]
	_ = x[OutStopDefence-69]
	_ = x[OutCrafting-87]
	_ = x[OutTitle-90]
	_ = x[OutDeathType-89]
	_ = x[OutChoice-96]
	_ = x[OutInteraction-97]
	_ = x[OutGetAdminInfo-98]
	_ = x[OutBreakPoint-99]
	_ = x[OutWarpMap-104]
	_ = x[OutLogOut-105]
	_ = x[OutGetPlayerInfo-107]
	_ = x[OutUpdatePlayerHonor-108]
	_ = x[OutUIBuddies-109]
	_ = x[OutCoupon-111]
	_ = x[OutCashShopUI-112]
	_ = x[OutFavAwards-113]
	_ = x[OutSelectMinigames-114]
	_ = x[OutDemoValue-115]
	_ = x[OutForgeAction-116]
	_ = x[OutCloseShop-53]
	_ = x[OutGetStats-38]
	_ = x[OutButton-40]
	_ = x[OutPlayerCommand-39]
	_ = x[OutCancel-117]
	_ = x[OutResetPassword-118]
	_ = x[OutGetUsername-119]
}

const (
	_ClientPacket_name_0 = "OutNewAccountOutLoginOutAddChar"
	_ClientPacket_name_1 = "OutPlayerMsgOutProfessionEndOutDragItemOutSayMsg"
	_ClientPacket_name_2 = "OutPlayerDirOutUseItemOutCheckAttackOutHotkeysOutHandlePressEnterOutWarpMeToOutWarpToMeOutAdminTaskOutChangePasswordOutUseMegaphoneOutClientRevisionOutMapOutMapEditorCancel"
	_ClientPacket_name_3 = "OutDropItemOutMapRespawnOutReportPlayerOutBanListOutEnhancementOutBanOutSaveItemOutSaveNpcOutSaveShopOutSaveSpellOutSetAccessOutWhosOnlineOutTryOpenUIOutPlayerSearchOutGetStatsOutPlayerCommandOutButton"
	_ClientPacket_name_4 = "OutCastingSpellOutTakeCaptureOutSwapSlotsOutSaveResourceOutGetPingOutUnequipOutSpawnItemOutTrainStatOutSaveAnimationOutRequestLevelUp"
	_ClientPacket_name_5 = "OutCloseShopOutBuyItemOutSellItemOutChangeBankSlotsOutDepositItemOutWithdrawItemOutCloseBankOutAdminWarpOutTradeRequestOutAcceptTradeOutDeclineTradeOutTradeItemOutUntradeItemOutRequestUseCharOutRequestNewCharOutRequestDelCharOutCheckDefensaOutChangeSpellSlotsOutHotbarChangeOutHotbarUseOutSaveQuestOutSelectedOutWhisperOutPartyRequestOutReplyPlayerInvitationOutDeclinePartyOutPartyLeaveOutSaveProjectilOutProjectilAttackOutSaveMoralOutRequestEditorOutSaveCardOutRequestDataOutSaveCraftingOutCrafting"
	_ClientPacket_name_6 = "OutDeathTypeOutTitleOutCheckTopoOutPVPOutSaveMapTopoOutSteamTransactionOutSaveConditionOutChoiceOutInteractionOutGetAdminInfoOutBreakPointOutSaveConditionVarOutSavePuzzleOutSaveComboOutLoginBackOutWarpMapOutLogOutOutUseCashItemOutGetPlayerInfoOutUpdatePlayerHonorOutUIBuddiesOutDropCalaverasOutCouponOutCashShopUIOutFavAwardsOutSelectMinigamesOutDemoValueOutForgeActionOutCancelOutResetPasswordOutGetUsername"
)

var (
	_ClientPacket_index_0 = [...]uint8{0, 13, 21, 31}
	_ClientPacket_index_1 = [...]uint8{0, 12, 28, 39, 48}
	_ClientPacket_index_2 = [...]uint8{0, 12, 22, 36, 46, 65, 76, 87, 99, 116, 131, 148, 154, 172}
	_ClientPacket_index_3 = [...]uint8{0, 11, 24, 39, 49, 63, 69, 80, 90, 101, 113, 125, 138, 150, 165, 176, 192, 201}
	_ClientPacket_index_4 = [...]uint8{0, 15, 29, 41, 56, 66, 76, 88, 100, 116, 133}
	_ClientPacket_index_5 = [...]uint16{0, 12, 22, 33, 51, 65, 80, 92, 104, 119, 133, 148, 160, 174, 191, 208, 225, 240, 259, 274, 286, 298, 309, 319, 334, 358, 373, 386, 402, 420, 432, 448, 459, 473, 488, 499}
	_ClientPacket_index_6 = [...]uint16{0, 12, 20, 32, 38, 52, 71, 87, 96, 110, 125, 138, 157, 170, 182, 194, 204, 213, 227, 243, 263, 275, 291, 300, 313, 325, 343, 355, 369, 378, 394, 408}
)

func (i ClientPacket) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _ClientPacket_name_0[_ClientPacket_index_0[i]:_ClientPacket_index_0[i+1]]
	case 5 <= i && i <= 8:
		i -= 5
		return _ClientPacket_name_1[_ClientPacket_index_1[i]:_ClientPacket_index_1[i+1]]
	case 10 <= i && i <= 22:
		i -= 10
		return _ClientPacket_name_2[_ClientPacket_index_2[i]:_ClientPacket_index_2[i+1]]
	case 24 <= i && i <= 40:
		i -= 24
		return _ClientPacket_name_3[_ClientPacket_index_3[i]:_ClientPacket_index_3[i+1]]
	case 42 <= i && i <= 51:
		i -= 42
		return _ClientPacket_name_4[_ClientPacket_index_4[i]:_ClientPacket_index_4[i+1]]
	case 53 <= i && i <= 87:
		i -= 53
		return _ClientPacket_name_5[_ClientPacket_index_5[i]:_ClientPacket_index_5[i+1]]
	case 89 <= i && i <= 119:
		i -= 89
		return _ClientPacket_name_6[_ClientPacket_index_6[i]:_ClientPacket_index_6[i+1]]
	default:
		return "ClientPacket(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
