// Code generated by "stringer -type=ServerPacket,ClientPacket -output=packet_enum_string.go"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlertMSG-1]
	_ = x[LoginOk-2]
	_ = x[ClassesData-3]
	_ = x[InGame-4]
	_ = x[PlayerInvUpdate-5]
	_ = x[PlayerWornEquipment-6]
	_ = x[PlayerVitals-7]
	_ = x[Coins-8]
	_ = x[Skulls-9]
	_ = x[PlayerStats-10]
	_ = x[PlayerData-11]
	_ = x[PlayerMove-12]
	_ = x[NpcMove-13]
	_ = x[PlayerDir-14]
	_ = x[NpcDir-15]
	_ = x[PlayerXY-16]
	_ = x[Attack-17]
	_ = x[NpcAttack-18]
	_ = x[CheckMap-19]
	_ = x[MapData-20]
	_ = x[MapItemData-21]
	_ = x[MapNPCData-22]
	_ = x[SteamAchievement-23]
	_ = x[GlobalMessage-24]
	_ = x[PlayerMessage-25]
	_ = x[MapMessage-26]
	_ = x[SpawnItem-27]
	_ = x[UpdateItem-28]
	_ = x[SpawnNPC-29]
	_ = x[NpcDead-30]
	_ = x[UpdateNPC-31]
	_ = x[UpdateShop-32]
	_ = x[UpdateSpell-33]
	_ = x[Spells-34]
	_ = x[PlayerTimer-35]
	_ = x[ResourceCache-36]
	_ = x[UpdateResource-37]
	_ = x[Ping-38]
	_ = x[ActionMessage-39]
	_ = x[PlayerExp-40]
	_ = x[PlayerSprite-41]
	_ = x[UpdateAnimation-42]
	_ = x[Animation-43]
	_ = x[MapNpcVitals-44]
	_ = x[Cooldown-45]
	_ = x[ClearSpellBuffer-46]
	_ = x[SayMessage-47]
	_ = x[OpenShop-48]
	_ = x[InspectPlayer-49]
	_ = x[Stunned-50]
	_ = x[MapWornEquipment-51]
	_ = x[Bank-52]
	_ = x[UpdateNewspaper-53]
	_ = x[PlayerCurrent-54]
	_ = x[Close-55]
	_ = x[TradeUpdate-56]
	_ = x[TradeStatus-57]
	_ = x[GameData-58]
	_ = x[HighIndex-59]
	_ = x[Target-60]
	_ = x[CharData-61]
	_ = x[Defensa-62]
	_ = x[UpdateQuest-63]
	_ = x[PlayerQuest-64]
	_ = x[SendTime-65]
	_ = x[SolarEXP-66]
	_ = x[PlayerInvite-67]
	_ = x[PartyUpdate-68]
	_ = x[PartyVitals-69]
	_ = x[BossMsg-70]
	_ = x[PlayerXYMap-71]
	_ = x[Projectil-72]
	_ = x[UpdateProjectil-73]
	_ = x[UpdateMoral-74]
	_ = x[Flash-75]
	_ = x[RequestEditor-76]
	_ = x[UpdateCard-77]
	_ = x[PlayerCards-78]
	_ = x[UpdateCrafting-79]
	_ = x[PlayerCrafting-80]
	_ = x[PlayerDeath-81]
	_ = x[UpdateTitle-82]
	_ = x[PlayerDataType-83]
	_ = x[BuffInfo-84]
	_ = x[SpellAnim-85]
	_ = x[BattleMsg-86]
	_ = x[NPCProjectil-87]
	_ = x[MapSound-88]
	_ = x[Arrow-89]
	_ = x[Bandit-90]
	_ = x[PlayerGameData-91]
	_ = x[PVP-92]
	_ = x[MapTopoData-93]
	_ = x[TopoDrill-94]
	_ = x[UpdateCondition-95]
	_ = x[ServerMsg-96]
	_ = x[DailyCheck-97]
	_ = x[SpawnMobItem-98]
	_ = x[ProjectilCross-99]
	_ = x[ReceiveHour-100]
	_ = x[ReceiveBubble-101]
	_ = x[Choice-102]
	_ = x[ClearChoice-103]
	_ = x[GetAdminInfo-104]
	_ = x[BreakPoint-105]
	_ = x[UpdateMapEvent-106]
	_ = x[SendConditionVar-107]
	_ = x[SendPlayerVars-108]
	_ = x[QuestMsg-109]
	_ = x[UpdatePuzzle-110]
	_ = x[UpdatePuzzleCache-111]
	_ = x[UpdatePlayerList-112]
	_ = x[Combo-113]
	_ = x[Tutorial-114]
	_ = x[PlayerElement-115]
	_ = x[PlayerRank-116]
	_ = x[Earthquake-117]
	_ = x[EventRank-118]
	_ = x[TravelInfo-119]
	_ = x[LoginBackOK-120]
	_ = x[PlayerAwards-121]
	_ = x[Awards-122]
	_ = x[CharacterConfirm-123]
	_ = x[OpenUI-124]
	_ = x[LogOutOK-125]
	_ = x[PlayerScore-126]
	_ = x[PartyQuestInfo-127]
	_ = x[DemoUpdateQuest-128]
	_ = x[CashInvUpdate-129]
	_ = x[PlayerInfo-130]
	_ = x[PlayerHonor-131]
	_ = x[PlayerBuddies-132]
	_ = x[BuddiesAction-133]
	_ = x[DrillBreak-134]
	_ = x[ArenaBonus-136]
	_ = x[NpcBuffInfo-137]
	_ = x[Announcer-138]
	_ = x[OpenBackground-139]
	_ = x[CouponReady-140]
	_ = x[ProfessionStart-141]
	_ = x[Modifier-142]
	_ = x[PlayerMaster-143]
	_ = x[Url-144]
	_ = x[PlayerStatus-145]
	_ = x[PlayerConnected-146]
	_ = x[ServerStats-147]
	_ = x[GetModInfo-148]
	_ = x[PlayerTrap-149]
	_ = x[ShowEmoticon-150]
	_ = x[ProfessionData-151]
	_ = x[ServerVars-152]
	_ = x[CashShopData-153]
	_ = x[BlockList-154]
	_ = x[ConstantData-155]
}

const (
	_ServerPacket_name_0 = "AlertMSGLoginOkClassesDataInGamePlayerInvUpdatePlayerWornEquipmentPlayerVitalsCoinsSkullsPlayerStatsPlayerDataPlayerMoveNpcMovePlayerDirNpcDirPlayerXYAttackNpcAttackCheckMapMapDataMapItemDataMapNPCDataSteamAchievementGlobalMessagePlayerMessageMapMessageSpawnItemUpdateItemSpawnNPCNpcDeadUpdateNPCUpdateShopUpdateSpellSpellsPlayerTimerResourceCacheUpdateResourcePingActionMessagePlayerExpPlayerSpriteUpdateAnimationAnimationMapNpcVitalsCooldownClearSpellBufferSayMessageOpenShopInspectPlayerStunnedMapWornEquipmentBankUpdateNewspaperPlayerCurrentCloseTradeUpdateTradeStatusGameDataHighIndexTargetCharDataDefensaUpdateQuestPlayerQuestSendTimeSolarEXPPlayerInvitePartyUpdatePartyVitalsBossMsgPlayerXYMapProjectilUpdateProjectilUpdateMoralFlashRequestEditorUpdateCardPlayerCardsUpdateCraftingPlayerCraftingPlayerDeathUpdateTitlePlayerDataTypeBuffInfoSpellAnimBattleMsgNPCProjectilMapSoundArrowBanditPlayerGameDataPVPMapTopoDataTopoDrillUpdateConditionServerMsgDailyCheckSpawnMobItemProjectilCrossReceiveHourReceiveBubbleChoiceClearChoiceGetAdminInfoBreakPointUpdateMapEventSendConditionVarSendPlayerVarsQuestMsgUpdatePuzzleUpdatePuzzleCacheUpdatePlayerListComboTutorialPlayerElementPlayerRankEarthquakeEventRankTravelInfoLoginBackOKPlayerAwardsAwardsCharacterConfirmOpenUILogOutOKPlayerScorePartyQuestInfoDemoUpdateQuestCashInvUpdatePlayerInfoPlayerHonorPlayerBuddiesBuddiesActionDrillBreak"
	_ServerPacket_name_1 = "ArenaBonusNpcBuffInfoAnnouncerOpenBackgroundCouponReadyProfessionStartModifierPlayerMasterUrlPlayerStatusPlayerConnectedServerStatsGetModInfoPlayerTrapShowEmoticonProfessionDataServerVarsCashShopDataBlockListConstantData"
)

var (
	_ServerPacket_index_0 = [...]uint16{0, 8, 15, 26, 32, 47, 66, 78, 83, 89, 100, 110, 120, 127, 136, 142, 150, 156, 165, 173, 180, 191, 201, 217, 230, 243, 253, 262, 272, 280, 287, 296, 306, 317, 323, 334, 347, 361, 365, 378, 387, 399, 414, 423, 435, 443, 459, 469, 477, 490, 497, 513, 517, 532, 545, 550, 561, 572, 580, 589, 595, 603, 610, 621, 632, 640, 648, 660, 671, 682, 689, 700, 709, 724, 735, 740, 753, 763, 774, 788, 802, 813, 824, 838, 846, 855, 864, 876, 884, 889, 895, 909, 912, 923, 932, 947, 956, 966, 978, 992, 1003, 1016, 1022, 1033, 1045, 1055, 1069, 1085, 1099, 1107, 1119, 1136, 1152, 1157, 1165, 1178, 1188, 1198, 1207, 1217, 1228, 1240, 1246, 1262, 1268, 1276, 1287, 1301, 1316, 1329, 1339, 1350, 1363, 1376, 1386}
	_ServerPacket_index_1 = [...]uint8{0, 10, 21, 30, 44, 55, 70, 78, 90, 93, 105, 120, 131, 141, 151, 163, 177, 187, 199, 208, 220}
)

func (i ServerPacket) String() string {
	switch {
	case 1 <= i && i <= 134:
		i -= 1
		return _ServerPacket_name_0[_ServerPacket_index_0[i]:_ServerPacket_index_0[i+1]]
	case 136 <= i && i <= 155:
		i -= 136
		return _ServerPacket_name_1[_ServerPacket_index_1[i]:_ServerPacket_index_1[i+1]]
	default:
		return "ServerPacket(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_SaveResource-45]
	_ = x[_SaveNpc-31]
	_ = x[_SaveItem-30]
	_ = x[_SavePuzzle-101]
	_ = x[_SaveSpell-33]
	_ = x[_SaveShop-32]
	_ = x[_SaveAnimation-50]
	_ = x[_ProjectilAttack-81]
	_ = x[_SaveProjectil-80]
	_ = x[_SaveMoral-82]
	_ = x[_SaveCard-84]
	_ = x[_SaveCrafting-86]
	_ = x[_SaveMapTopo-93]
	_ = x[_SteamTransaction-94]
	_ = x[_SaveCondition-95]
	_ = x[_SaveConditionVar-100]
	_ = x[_SaveQuest-73]
	_ = x[_CheckAttack-12]
	_ = x[_CheckTopo-91]
	_ = x[_CheckDefensa-69]
	_ = x[_HandlePressEnter-14]
	_ = x[_CastingSpell-42]
	_ = x[_PVP-92]
	_ = x[_MapEditorCancel-22]
	_ = x[_RequestEditor-83]
	_ = x[_Selected-74]
	_ = x[_NewAccount-1]
	_ = x[_AddChar-3]
	_ = x[_Login-2]
	_ = x[_GetPing-46]
	_ = x[_ChangeSpellSlots-70]
	_ = x[_HotbarChange-71]
	_ = x[_Map-21]
	_ = x[_PlayerDir-10]
	_ = x[_SayMsg-8]
	_ = x[_ReportPlayer-26]
	_ = x[_Ban-29]
	_ = x[_Hotkeys-13]
	_ = x[_WarpMeTo-15]
	_ = x[_WarpToMe-16]
	_ = x[_AdminTask-17]
	_ = x[_SetAccess-34]
	_ = x[_TakeCapture-43]
	_ = x[_SpawnItem-48]
	_ = x[_RequestLevelUp-51]
	_ = x[_ChangePassword-18]
	_ = x[_LoginBack-103]
	_ = x[_Whisper-75]
	_ = x[_HotbarUse-72]
	_ = x[_UseMegaphone-19]
	_ = x[_ClientRevision-20]
	_ = x[_SaveCombo-102]
	_ = x[_PartyLeave-79]
	_ = x[_PartyRequest-76]
	_ = x[_ReplyPlayerInvitation-77]
	_ = x[_DeclineParty-78]
	_ = x[_RequestData-85]
	_ = x[_Enhancement-28]
	_ = x[_MapRespawn-25]
	_ = x[_TrainStat-49]
	_ = x[_DragItem-7]
	_ = x[_ProfessionEnd-6]
	_ = x[_PlayerMsg-5]
	_ = x[_WhosOnline-35]
	_ = x[_TryOpenUI-36]
	_ = x[_BanList-27]
	_ = x[_SwapSlots-44]
	_ = x[_UseItem-11]
	_ = x[_UseCashItem-106]
	_ = x[_DropCalaveras-110]
	_ = x[_DropItem-24]
	_ = x[_BuyItem-54]
	_ = x[_SellItem-55]
	_ = x[_DepositItem-57]
	_ = x[_WithdrawItem-58]
	_ = x[_ChangeBankSlots-56]
	_ = x[_CloseBank-59]
	_ = x[_PlayerSearch-37]
	_ = x[_TradeRequest-61]
	_ = x[_AdminWarp-60]
	_ = x[_Unequip-47]
	_ = x[_AcceptTrade-62]
	_ = x[_DeclineTrade-63]
	_ = x[_TradeItem-64]
	_ = x[_UntradeItem-65]
	_ = x[_RequestUseChar-66]
	_ = x[_RequestNewChar-67]
	_ = x[_RequestDelChar-68]
	_ = x[_StopDefence-69]
	_ = x[_Crafting-87]
	_ = x[_Title-90]
	_ = x[_DeathType-89]
	_ = x[_Choice-96]
	_ = x[_Interaction-97]
	_ = x[_GetAdminInfo-98]
	_ = x[_BreakPoint-99]
	_ = x[_WarpMap-104]
	_ = x[_LogOut-105]
	_ = x[_GetPlayerInfo-107]
	_ = x[_UpdatePlayerHonor-108]
	_ = x[_UIBuddies-109]
	_ = x[_Coupon-111]
	_ = x[_CashShopUI-112]
	_ = x[_FavAwards-113]
	_ = x[_SelectMinigames-114]
	_ = x[_DemoValue-115]
	_ = x[_ForgeAction-116]
	_ = x[_CloseShop-53]
	_ = x[_GetStats-38]
	_ = x[_Button-40]
	_ = x[_PlayerCommand-39]
	_ = x[_Cancel-117]
	_ = x[_ResetPassword-118]
	_ = x[_GetUsername-119]
}

const (
	_ClientPacket_name_0 = "_NewAccount_Login_AddChar"
	_ClientPacket_name_1 = "_PlayerMsg_ProfessionEnd_DragItem_SayMsg"
	_ClientPacket_name_2 = "_PlayerDir_UseItem_CheckAttack_Hotkeys_HandlePressEnter_WarpMeTo_WarpToMe_AdminTask_ChangePassword_UseMegaphone_ClientRevision_Map_MapEditorCancel"
	_ClientPacket_name_3 = "_DropItem_MapRespawn_ReportPlayer_BanList_Enhancement_Ban_SaveItem_SaveNpc_SaveShop_SaveSpell_SetAccess_WhosOnline_TryOpenUI_PlayerSearch_GetStats_PlayerCommand_Button"
	_ClientPacket_name_4 = "_CastingSpell_TakeCapture_SwapSlots_SaveResource_GetPing_Unequip_SpawnItem_TrainStat_SaveAnimation_RequestLevelUp"
	_ClientPacket_name_5 = "_CloseShop_BuyItem_SellItem_ChangeBankSlots_DepositItem_WithdrawItem_CloseBank_AdminWarp_TradeRequest_AcceptTrade_DeclineTrade_TradeItem_UntradeItem_RequestUseChar_RequestNewChar_RequestDelChar_CheckDefensa_ChangeSpellSlots_HotbarChange_HotbarUse_SaveQuest_Selected_Whisper_PartyRequest_ReplyPlayerInvitation_DeclineParty_PartyLeave_SaveProjectil_ProjectilAttack_SaveMoral_RequestEditor_SaveCard_RequestData_SaveCrafting_Crafting"
	_ClientPacket_name_6 = "_DeathType_Title_CheckTopo_PVP_SaveMapTopo_SteamTransaction_SaveCondition_Choice_Interaction_GetAdminInfo_BreakPoint_SaveConditionVar_SavePuzzle_SaveCombo_LoginBack_WarpMap_LogOut_UseCashItem_GetPlayerInfo_UpdatePlayerHonor_UIBuddies_DropCalaveras_Coupon_CashShopUI_FavAwards_SelectMinigames_DemoValue_ForgeAction_Cancel_ResetPassword_GetUsername"
)

var (
	_ClientPacket_index_0 = [...]uint8{0, 11, 17, 25}
	_ClientPacket_index_1 = [...]uint8{0, 10, 24, 33, 40}
	_ClientPacket_index_2 = [...]uint8{0, 10, 18, 30, 38, 55, 64, 73, 83, 98, 111, 126, 130, 146}
	_ClientPacket_index_3 = [...]uint8{0, 9, 20, 33, 41, 53, 57, 66, 74, 83, 93, 103, 114, 124, 137, 146, 160, 167}
	_ClientPacket_index_4 = [...]uint8{0, 13, 25, 35, 48, 56, 64, 74, 84, 98, 113}
	_ClientPacket_index_5 = [...]uint16{0, 10, 18, 27, 43, 55, 68, 78, 88, 101, 113, 126, 136, 148, 163, 178, 193, 206, 223, 236, 246, 256, 265, 273, 286, 308, 321, 332, 346, 362, 372, 386, 395, 407, 420, 429}
	_ClientPacket_index_6 = [...]uint16{0, 10, 16, 26, 30, 42, 59, 73, 80, 92, 105, 116, 133, 144, 154, 164, 172, 179, 191, 205, 223, 233, 247, 254, 265, 275, 291, 301, 313, 320, 334, 346}
)

func (i ClientPacket) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _ClientPacket_name_0[_ClientPacket_index_0[i]:_ClientPacket_index_0[i+1]]
	case 5 <= i && i <= 8:
		i -= 5
		return _ClientPacket_name_1[_ClientPacket_index_1[i]:_ClientPacket_index_1[i+1]]
	case 10 <= i && i <= 22:
		i -= 10
		return _ClientPacket_name_2[_ClientPacket_index_2[i]:_ClientPacket_index_2[i+1]]
	case 24 <= i && i <= 40:
		i -= 24
		return _ClientPacket_name_3[_ClientPacket_index_3[i]:_ClientPacket_index_3[i+1]]
	case 42 <= i && i <= 51:
		i -= 42
		return _ClientPacket_name_4[_ClientPacket_index_4[i]:_ClientPacket_index_4[i+1]]
	case 53 <= i && i <= 87:
		i -= 53
		return _ClientPacket_name_5[_ClientPacket_index_5[i]:_ClientPacket_index_5[i+1]]
	case 89 <= i && i <= 119:
		i -= 89
		return _ClientPacket_name_6[_ClientPacket_index_6[i]:_ClientPacket_index_6[i+1]]
	default:
		return "ClientPacket(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
